Repository COS301-SE-2024/Events-System, pull requests merged in 2024-06, with the labels that each got.

#23 Feat/testing
  .github/workflows/Unit-test.yml
  e2e/src/example.spec.ts
  package-lock.json
  package.json
  scripts/frontend-start.bash
Labels: bug, documentation

#24 PR main to develop to begin develop
  .github/workflows/Unit-test.yml
  e2e/src/example.spec.ts
  package-lock.json
  package.json
  scripts/frontend-start.bash
Labels: enhancement

#27 calender page
  src/Components/Calender-Event-Button/Calender-Event-button.component.css
  src/Components/Calender-Event-Button/Calender-Event-button.component.html
  src/Components/Calender-Event-Button/Calender-Event-button.component.spec.ts
  src/Components/Calender-Event-Button/Calender-Event-button.component.ts
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.routes.ts
  src/calender/calender.component.css
  src/calender/calender.component.html
  src/calender/calender.component.spec.ts
  src/calender/calender.component.ts
  src/profile/profile.component.css
  src/profile/profile.component.html
  src/profile/profile.component.spec.ts
  src/profile/profile.component.ts
  src/settings/settings.component.spec.ts
Labels: bug, enhancement

#37 Feat/welcome
  project.json
  proxy.conf.json
  src/Components/event/event.component.css
  src/Components/event/event.component.html
  src/Components/event/event.component.spec.ts
  src/Components/event/event.component.ts
  src/app/app.component.html
  src/app/app.routes.ts
  src/events/events.component.css
  src/events/events.component.html
  src/events/events.component.spec.ts
  src/events/events.component.ts
Labels: enhancement

#38 fixed failing tests, fixed linter
  Backend/src/main/resources/application.properties
  package-lock.json
  package.json
  src/Components/userProfileComponent/userProfile.component.ts
  src/events/events.component.spec.ts
  src/events/events.component.ts
  src/test-setup.ts
Labels: bug, enhancement

#55 Removed credentials from repo
  .github/workflows/ci.yml
  .gitignore
  Backend/.gitignore
  Backend/app.yml
  Backend/src/main/resources/application.properties
  backend-deploy.bash
Labels: bug

#76 added events page
  Backend/build.gradle
  Backend/src/main/resources/application.properties
  src/Components/EventCard/eventCard.component.css
  src/Components/EventCard/eventCard.component.html
  src/Components/EventCard/eventCard.component.spec.ts
  src/Components/EventCard/eventCard.component.ts
  src/Components/GhostEventCard/GhostEventCard.component.css
  src/Components/GhostEventCard/GhostEventCard.component.html
  src/Components/GhostEventCard/GhostEventCard.component.spec.ts
  src/Components/GhostEventCard/GhostEventCard.component.ts
  src/Components/event/event.component.ts
  src/events/events.component.html
  src/events/events.component.ts
  src/index.html
  src/login/login.component.html
  tailwind.config.js
Labels: enhancement

#94 Bug fixes and introduction of e2e testing
  .github/workflows/e2e-tests.yml
  .github/workflows/unit-tests.yml
  Backend/src/main/java/com/back/demo/auth/AuthenticationController.java
  e2e/src/events.spec.ts
  e2e/src/example.spec.ts
  package-lock.json
  package.json
  src/CreateEvent/CreateEvent.component.html
  src/CreateEvent/CreateEvent.component.ts
  src/UpdateEvent/UpdateEvent.component.html
  src/UpdateEvent/UpdateEvent.component.ts
  src/login/login.component.ts
  src/profile/profile.component.ts
  src/settings/settings.component.ts
  test-results/.last-run.json
Labels: enhancement

#95 Bug fixes and introduction of e2e testing (#94)
  .github/workflows/e2e-tests.yml
  .github/workflows/unit-tests.yml
  Backend/src/main/java/com/back/demo/auth/AuthenticationController.java
  e2e/src/events.spec.ts
  e2e/src/example.spec.ts
  package-lock.json
  package.json
  src/CreateEvent/CreateEvent.component.html
  src/CreateEvent/CreateEvent.component.ts
  src/UpdateEvent/UpdateEvent.component.html
  src/UpdateEvent/UpdateEvent.component.ts
  src/login/login.component.ts
  src/profile/profile.component.ts
  src/settings/settings.component.ts
  test-results/.last-run.json
Labels: documentation, enhancement
